version: "3"
services:
    redis:
        image: redis
        networks:
            - py
    pycore:
        image: pycore
        environment:
            DB_USER: 'root'
            DB_PASS: 'robinhood'
            DB_HOST: 'postgres'
            DB_NAME: 'robin'
            SERVER_ENV: 'Development'
            APP_NAME: 'app'
            SECRET_KEY: 'key'
            SECURITY_PASSWORD_SALT: 'salt'
        networks:
            - py
        ports:
            - "80:8008"
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9000:9000"
        deploy:
            placement:
                constraints: [node.role == manager]
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'robinhood'
            MYSQL_DATABASE: 'robin'
        ports:
            - "3306:3306"
        volumes:
            - "~/swarm/mysql:/var/lib/mysql"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - py
    influx:
        image: "influxdb:latest"
        environment:
            INFLUXDB_GRAPHITE_ENABLED: 'true'
            INFLUXDB_ADMIN_ENABLED: 'true'
        ports:
            - "8083:8083"
            - "8086:8086"
            - "2003"
        volumes:
            - "~/influxdb:/var/lib/influxdb"
        networks:
            - py
networks:
    py:
